name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo join(github.event.issue.labels.*.name, ', ')
      - name: condition testing
        env:
          CONDITION: ${{ contains('skip this tag', 'skip') }}
        run: echo "Condition is $CONDITION"
      - name: test "#skip" in commit messages
        if: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
        run: echo "This step is executed because '#skip' is found in commit messages."